integration testing web

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -30,51 +30,51 @@
 
 
 
-definitions:
-  cool_vars: &cool_vars
-    meow: 'testing'
-  instance_mac_pro: &instance_mac_pro
-    instance_type: mac_mini_m1
-    max_build_duration: 120
-  env_versions: &env_versions
-    flutter: stable
-    xcode: 13.4.1
-    cocoapods: default
-  triggering:
-    events:
-      - tag             
-    tag_patterns:
-      - pattern: '*'
-        include: true
-  environment:
-    automatic_ios_signing: &automatic_ios_signing
-      groups:
-        - appstore_credentials
-        - ios
-        - test_ios
-      vars:
-        BUNDLE_ID: "com.example.kobitionIntegration"
-        XCODE_WORKSPACE: "App.xcworspace"
-        XCODE_SCHEME: "App"
-        XCODE_CONFIG: "Release-dev"
-#     browserstack_upload: &browserstack_upload
+# definitions:
+#   cool_vars: &cool_vars
+#     meow: 'testing'
+#   instance_mac_pro: &instance_mac_pro
+#     instance_type: mac_mini_m1
+#     max_build_duration: 120
+#   env_versions: &env_versions
+#     flutter: stable
+#     xcode: 13.4.1
+#     cocoapods: default
+#   triggering:
+#     events:
+#       - tag             
+#     tag_patterns:
+#       - pattern: '*'
+#         include: true
+#   environment:
+#     automatic_ios_signing: &automatic_ios_signing
 #       groups:
-#          - appstore_credentials
+#         - appstore_credentials
+#         - ios
+#         - test_ios
 #       vars:
-#         TEST: '123'
+#         BUNDLE_ID: "com.example.kobitionIntegration"
+#         XCODE_WORKSPACE: "App.xcworspace"
+#         XCODE_SCHEME: "App"
+#         XCODE_CONFIG: "Release-dev"
+# #     browserstack_upload: &browserstack_upload
+# #       groups:
+# #          - appstore_credentials
+# #       vars:
+# #         TEST: '123'
 
 
-workflows:
-  ios-workflow:
-    name: iOS Workflow
-    <<: *instance_mac_pro
-    environment:
-        <<: *env_versions
-        <<: *automatic_ios_signing
-        flutter: 3.3.6
-        xcode: 14.1
-        cocoapods: default
-        node: 16.16.0
+# workflows:
+#   ios-workflow:
+#     name: iOS Workflow
+#     <<: *instance_mac_pro
+#     environment:
+#         <<: *env_versions
+#         <<: *automatic_ios_signing
+#         flutter: 3.3.6
+#         xcode: 14.1
+#         cocoapods: default
+#         node: 16.16.0
 #     triggering:
 #       events:                   
 #         - pull_request
@@ -88,49 +88,49 @@ workflows:
 #         includes:
 #           - '.'
                  
-    scripts:
-#       - name: Firebase
-#         script: |
-#           flutter pub add firebase_core
-#           flutter pub add firebase_messaging
-      # - name: Clean-up
-      #   script: |
-      #     rm -rf /Applications/Xcode-13.3.app
-      #     rm -rf /Applications/Xcode-13.4.app
-      #     rm -rf /Applications/Xcode-14.0.app
+#     scripts:
+# #       - name: Firebase
+# #         script: |
+# #           flutter pub add firebase_core
+# #           flutter pub add firebase_messaging
+#       # - name: Clean-up
+#       #   script: |
+#       #     rm -rf /Applications/Xcode-13.3.app
+#       #     rm -rf /Applications/Xcode-13.4.app
+#       #     rm -rf /Applications/Xcode-14.0.app
     
-      - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
-        script: |
-          keychain initialize
-          # /usr/local/bin/docker --version
-          # echo $PRODUCT_BUILD_NUMBER
-          # echo $BUILD_NUMBER
-      - name: Fetch signing files
-        script: |
-          app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
-      - name: Use system default keychain
-        script: |
-          keychain add-certificates
-#       - *codesign
-      - name: Set up code signing settings on Xcode project
-        script: |
-          xcode-project use-profiles
-      - name: Get Flutter packages
-        script: |
-          cd . && flutter packages pub get
-      - name: Install pods
-        script: |
-          find . -name "Podfile" -execdir pod install \;
+#       - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
+#         script: |
+#           keychain initialize
+#           # /usr/local/bin/docker --version
+#           # echo $PRODUCT_BUILD_NUMBER
+#           # echo $BUILD_NUMBER
+#       - name: Fetch signing files
+#         script: |
+#           app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
+#       - name: Use system default keychain
+#         script: |
+#           keychain add-certificates
+# #       - *codesign
+#       - name: Set up code signing settings on Xcode project
+#         script: |
+#           xcode-project use-profiles
+#       - name: Get Flutter packages
+#         script: |
+#           cd . && flutter packages pub get
+#       - name: Install pods
+#         script: |
+#           find . -name "Podfile" -execdir pod install \;
      
           
-#       - name: Flutter Integration Tests iOS
+# #       - name: Flutter Integration Tests iOS
+# #         script: |
+# #            flutter emulators --launch apple_ios_simulator
+# #            xcrun simctl boot 0B315533-768E-47B9-AC74-94CDF3FAE84F
+# #            flutter -d 0B315533-768E-47B9-AC74-94CDF3FAE84F test integration_test
+#       - name: Flutter build ipa and automatic versioning
 #         script: |
-#            flutter emulators --launch apple_ios_simulator
-#            xcrun simctl boot 0B315533-768E-47B9-AC74-94CDF3FAE84F
-#            flutter -d 0B315533-768E-47B9-AC74-94CDF3FAE84F test integration_test
-      - name: Flutter build ipa and automatic versioning
-        script: |
-          flutter build ipa --release --dart-define=OPENOCEAN_APP_SUFFIX=.internal --dart-define=OPENOCEAN_APP_JIRA_COLLECTOR_ID=74f19d0b --dart-define=OPENOCEAN_APP_ONE_SIGNAL_APP_ID=ebf7a548-3feb-4fc0-bf87-361b29db98e6 --dart-define=OPENOCEAN_APP_MAP_BOX_ACCESS_TOKEN=pk.eyJ1IjoicGF1bGJpcmtpbiIsImEiOiJjamt0ZHV5YzkwNDl0M3dtcmhrbjF5NmozIn0.RUGTvUZkWgOVyv9dJvqm_Q --export-options-plist=/Users/builder/export_options.plist
+#           flutter build ipa --release --dart-define=OPENOCEAN_APP_SUFFIX=.internal --dart-define=OPENOCEAN_APP_JIRA_COLLECTOR_ID=74f19d0b --dart-define=OPENOCEAN_APP_ONE_SIGNAL_APP_ID=ebf7a548-3feb-4fc0-bf87-361b29db98e6 --dart-define=OPENOCEAN_APP_MAP_BOX_ACCESS_TOKEN=pk.eyJ1IjoicGF1bGJpcmtpbiIsImEiOiJjamt0ZHV5YzkwNDl0M3dtcmhrbjF5NmozIn0.RUGTvUZkWgOVyv9dJvqm_Q --export-options-plist=/Users/builder/export_options.plist
 #       - name: Set the app URL and PATH
 #         script: | 
 #               CURL_RESULT=$( curl -X POST https://api.kobiton.com/v1/apps/uploadUrl \
@@ -204,15 +204,15 @@ workflows:
 #                   -H 'Authorization: Basic $KOBITON_CREDENTIALS' \
 #                   -H 'Content-Type: application/json' \
 #                   -H 'Accept: application/json'
-    artifacts:
-      - build/ios/ipa/*.ipa
-      - /tmp/xcodebuild_logs/*.log
-      - flutter_drive.log
-    publishing:
-      app_store_connect:
-        api_key: $APP_STORE_CONNECT_PRIVATE_KEY         
-        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER       
-        issuer_id: $APP_STORE_CONNECT_ISSUER_ID         
+    # artifacts:
+    #   - build/ios/ipa/*.ipa
+    #   - /tmp/xcodebuild_logs/*.log
+    #   - flutter_drive.log
+    # publishing:
+    #   app_store_connect:
+    #     api_key: $APP_STORE_CONNECT_PRIVATE_KEY         
+    #     key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER       
+    #     issuer_id: $APP_STORE_CONNECT_ISSUER_ID         
         # submit_to_app_store: true 
         # release_type: AFTER_APPROVAL
 
@@ -302,3 +302,29 @@ workflows:
 #                 emulator -avd emulator &
 #                 adb wait-for-device
 
+workflows:
+ reproduction-web-integration-tests:
+    name: Web Integration Test Workflow
+    instance_type: mac_mini_m1
+    environment:
+      flutter: 3.3.9
+      xcode: latest
+      cocoapods: default
+    scripts:
+      - |
+        #!/usr/bin/env sh
+        set -e # exit on first failed command
+        echo "Install supported chromedriver"
+        CHROME_VERSION=`/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --version | awk '{print $3}'`
+        CHROME_VERSION_WITHOUT_BUILD_NUMBER=`awk -F '.' '{print $1,$2,$3}' OFS='.' <<< $CHROME_VERSION` 
+        CHROMEDRIVER_VERSION=`curl -0 https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION_WITHOUT_BUILD_NUMBER`
+        curl -O https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_mac64.zip
+        unzip chromedriver_mac64
+        echo "Installed chromedriver $CHROMEDRIVER_VERSION"
+      - flutter packages pub get
+      - flutter config --enable-web
+      - ./chromedriver --port=4444 &
+      - flutter -d chrome drive --driver=test_driver/integration_driver.dart --target=integration_test/app_test.dart
+
+    artifacts:
+      - flutter_drive.log
